name: Generate sitemap

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: "https://www.femkehulsman.nl"
          sitemap-format: "xml"
      - name: Commit sitemap
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add sitemap.xml
          git commit -m "Add sitemap"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:sitemap-branch



